title: Supervision guide. {{< fa graduation-cap >}}
# quarto add quarto-ext/fontawesome
author: Dr. Martín Lozano.
date-modified: now
date-format: "MMMM D, YYYY, HH:mm:ss a."


abstract: This document is subject to changes due to new regulations dictated by the programme management, academic department and/or the university. It is also subject to a new and improved set of recommendations given my experience using this document in the past. Please note that all recommendations and guidance in this document apply for students that agree to work under my supervision in Mexico and UK. If there is any discrepancy between this document and the official guidelines or regulations dictated by the academic programme or the university, then the rule is to follow the official guidelines. This document is a work in progress, and not all the material taken from publicly available sources has been properly referenced.
bibliography: references.bib
  
theme:
  light: flatly
  dark: darkly
    
format: 
  html:
    toc: true
    toc-title: Contents
    smooth-scroll: true
    code-fold: false
    code-tools:
      source: false
      toggle: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-line-numbers: true
    number-sections: true
    crossref:
      chapters: true
    toc-location: left
    toc-depth: 2
    page-layout: full
    include-after-body: analytics_supervision.html
    include-in-header: 
      - back-to-top.html
      - progressbar.html
    css: styles.css
link-citations: true