---
title: Supervision guide `r fontawesome::fa("r-project")` <span style="color:white">R</span>

subtitle: Dr. Martín Lozano.
author:
#- name: Back to main [`r fontawesome::fa("home")`](https://mlozanoqf.github.io/)
#  affiliation: Academic website. [Web.](https://sites.google.com/site/mlozanoqf/)
date: Current `r fontawesome::fa("code-commit") ` `r format(Sys.time(), '%d %b %Y, %H:%M:%S.')`
#  bookdown::gitbook: default
output: 
  bookdown::html_document2:
    toc: yes
    toc_float: yes
    toc_depth: 2
    number_sections: yes
    fig_caption: yes
    code_folding: hide
    theme: readable #darkly 
    includes:
     # after_body: analytics_if.html
abstract: This document is subject to changes due to new regulations dictated by the programme management, academic department and/or the university. It is also subject to new and improved set of recommendations given my experience using this document in the past. Please note that all recommendations and guidance in this document apply only for students that agree to work under my supervision. If there is any discrepancy between this document and the official guidelines dictated by the academic programme, then the rule is to follow the official guidelines. This document is a work in progress, and not all the material taken from publicly available sources has been properly referenced.
bibliography: references.bib
---

```{=tex}
\newpage 
\hypersetup{linkcolor=black}
\renewcommand*\contentsname{Index.}
\tableofcontents
```

```{r include=FALSE}
# This removes all items in environment. 
# It is a good practice to start your code this way.
rm(list=ls())
library(fontawesome)
library(tictoc)
tic()
```

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
knitr::opts_chunk$set(fig.pos = "H", out.extra = "")
```

```{r, xaringanExtra-clipboard, echo=FALSE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa fa-clone fa-2x\" style=\"color: #301e64\"></i>",
    success_text = "<i class=\"fa fa-check fa-2x\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times fa-2x\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
```

````{=html}
```{r, echo=FALSE, results='asis'}
xfun::file_string('contact.html')
```
````

# [`r fa("arrow-circle-left", fill = "black")`](https://mlozanoqf.github.io/) [<span style="color: black">Back to QFR.</span>](https://mlozanoqf.github.io/) {-}

# [`r fa("arrow-circle-up", fill = "black")`](https://mlozanoqf.github.io/tutorial_if/) [<span style="color: black">Back to top.</span>](https://mlozanoqf.github.io/tutorial_if/) {-}

\newpage

```{r strategies, child = 'guide.Rmd'}
```



```{r include=FALSE}
a <- toc()
```

This document took `r round(as.numeric((a$toc-a$tic)/60), 2)` minutes to compile in Rmarkdown, `r R.version.string`.

# References.


