---
title: ''
#output: bookdown::gitbook:
  html_document:
    df_print: paged
---

```{r echo=FALSE}
# This removes all items in environment. 
rm(list=ls())
```

\newpage

# `r fontawesome::fa("handshake")` Introduction.

Welcome `r fontawesome::fa("laugh")`. If you are reading this document, it is because we have agreed or we are in the process of agreeing that I will supervise your project, thesis, or dissertation whether it is research oriented, or consultancy based. In short, I will simply use the word project from now on. I am confident that we can develop an interesting project, and I have high expectations about your overall performance as an individual and more importantly as a team. You should be confident that I have more than enough academic credentials, experience, and interest to help you in this process regardless the scope, approach, and the topic of your project. You can find my full and updated academic curriculum [here](https://sites.google.com/site/mlozanoqf/) This is the Zoom link for meetings: https://us02web.zoom.us/j/9209945512. Once again, welcome.

The objective of this document is twofold: (1) explain the supervision process, and (2) explain the project contents and structure.

Our common goal is to produce a solid and interesting project which meets the university quality standards, my own expectations as supervisor, and your own interests as students. I expect the best academic performance that you can achieve, and perhaps even more. You must expect me to support you and guide you in the best way possible to achieve our ultimate objective which is to produce a high-quality project and communicate its significance with authority. For this purpose, you also must know that from now on, part of my time, my knowledge, interest, and experience are currently at your service. I enjoy the supervision process because I always meet extraordinary people that creates an interesting project in a subject that I find interesting. 

You should know that there are several kinds of projects or thesis depending on their scope, originality and contribution to the professional or academic field. We can broadly differentiate between undergraduate (not very common), master, and PhD thesis. All of them should aim to contribute to the academic and/or professional field at differentiated levels, and represent clear evidence that the candidate or the student is an expert in his or her area of study. However, the level, depth, impact, quality, and significance of that contribution depend on many factors. These include: the aspired academic degree, the time availability, the academic rigor of the designated supervisor, and/or the general quality standards of the university and/or academic department. 

Your project represents a way to differentiate yourself among the rest of your colleagues in the job market as you may have the same degree but different project topic. I will try to clearly communicate whether you are meeting my own standards because this will influence the mark you will officially receive in your academic records. In any case, you can ask me directly whether you are meeting my expectations and I will answer as clearly as possible. This may be obvious, but you should know we (students and supervisor) are not competing, we are collaborating to reach our final objective which is to end up with a high-quality project to submit on time. I will also try to keep a respectful, professional, and friendly relationship to facilitate our communication and contribute to reach our final objective.

Your thesis project is also an opportunity to develop or engender your current research skills. Research skills are not exclusive for consolidated researchers, leading authors, and academics with a PhD degree. Research skills are also very important in the current job market and industry which nowadays has become highly competitive and demands professionals with a formal approach to address and solve problems following a modern and innovative scientific approach. Problems that already exist in the industry, and those that do not exist yet. A professional with the ability to learn, innovate, and develop applied research projects, are very valuable in the job market. You are expected to be good at learning well and fast by yourself, and gathering research skills can help you in this respect. It is not easy to gather research skills alone and isolated from academia, this is why one typical way to get them is by letting experienced researchers train enthusiastic students. 

You are not only going to develop new skills during the supervision period. Ideally, you will also have the opportunity to use your current professional skills and specialization to address the project objectives. Then, it is important to let me know who you are so we can take advantage of your unique and distinctive professional skills and abilities to develop an interesting project.

# `r fontawesome::fa("question-circle")` Frequently asked questions.

Here are a few frequently asked questions that most of my students have about their projects:

1. **Who is supposed to propose the project topic?**
*There are several ways to proceed in this respect. One typical way is that students declare their main interests; then I can propose several alternatives; and we can discuss until we define the most appropriate project for you. Proposing topics that you as a student do not want to do is also a valid way to define the project topic. Another way is that students pick from a list, so programme administrators can match students and supervisors.*

2. **Are there any restrictions or limitations in terms of the topics you can supervise?**
*Not really. I can supervise a wide variety of consultancy oriented or research projects in the area of business, economics, statistics, data science, finance, management, its combinations, extensions, sub-areas, and other more specific and newer topics. I have a marked preference to select a quantitative approach in the area of economics and/or finance, but in short there are virtually no restrictions in terms of the topics I can supervise.*

3. **Are we supposed to produce a very long and complicated R code?**
*Your project, and more specifically the empirical section that will lead to your original results will most likely be developed in R given the quantitative nature of the project that I will try to pursue with you. However, I strongly believe that the project contribution is far more important than the methodology or the specific way or software to produce results. Therefore, your thesis could be intense in computer programming or not. This will depend on the project itself, our discussion, your ability to do computer programming, objectives, and scope. A project that relies on computer programming is usually more ambitious and with a more interesting contribution as it has virtually no barriers or frontiers in terms of data analysis and reaching original findings. In short, the answer is: it depends.*

4. **Is there a minimum and maximum page limit for my project?**
*You should look at the official guidelines for this. In my personal view, the extension is mostly determined by the achievement of the project objectives and not in the number of pages. Page number is not necessarily related with project quality, but I understand it can be used to meet some standards dictated by the academic programme. In any case, I will decide whether a specific section in your project is sufficiently developed or not. Just as a reference, John Nash's thesis was 26 pages, and had two references in the bibliography. It is also true that few pages can be a sign of a lack of a deep analysis. In short, I will clearly inform you in case you are falling too short in terms of page limit. If I do not do that, then you have the obligation to ask.*

5. **What would be your very best recommendation for us as students?**
*Inform me regularly about your progress, and incorporate all my feedback in your progress. Read this document on a regular basis. Keep quality standards as high as possible. If for any reason I take too long to answer you back, please insist. *

6. **Do you ask for weekly progress reports?**
*Not really. I rather prefer to ask for reports based on tasks or tasks progress. The process is rather simple: you send me a draft, I give you comments by email and/or Zoom, you incorporate my comments, you send me a new draft, and the process start again. This is the Zoom link for meetings: https://us02web.zoom.us/j/9209945512. *

7. **Are we going to write our project in MS-Word?**
*There are several alternatives to write your project. You can use MS-Word, Google Docs, Overleaf, R Markdown, or any other $\LaTeX{}$ compiler.*

8. **We are a team. Are we going to have the same individual mark?**
*Not necessarily. I may include auto and co-evaluations to know more about your view about the team members contribution to the team work.*

9. **How frequent are we going to communicate with you?**
*There might be an answer in the official student guidelines dictated by the academic programme. However, in my case you are free to contact me whenever you need. I am interested that you understand what has to be done so I can answer questions by email or have Zoom meetings to make that clear. You are expected to show that you can work independently, but this does not mean that you will be alone in the process. So, feel free to contact me.*

10. **More in future versions of this document.**
