# `r fontawesome::fa("calendar-alt")` UDEM: Calendario MIN. 

MIN, Primavera 2026. Salón 3310, Jueves 19:00 – 22:00. Zoom URL para unirse: [https://us02web.zoom.us/j/82399571470](https://us02web.zoom.us/j/82399571470)


## `r fontawesome::fa("battery-quarter", fill = "grey")` Part 1.

**Session 1. `r fontawesome::fa("handshake")` Thursday, January 15.**

- Bienvenida.
- ¿Tienes equipo, tema y asesor(a)?
- Tema: Tipos de tesis, su estructura y expectativas sobre su trabajo PEF.
- Mensaje: *El tema de tu tesis no se define en una lluvia de ideas, sino que surge revisando la literatura, con la ayuda de Google Scholar, ChatGPT y tu profesor.*
- Tema: Uso de [Google Scholar](https://scholar.google.com/) en la definición del tema y bases de datos.
- Si tienes interés en una licencia de DataCamp para este semestre envíame un email para dártela.
- Al menos durante este semestre es necesario que te suscribas al canal de YouTube [ahyaentendi](https://www.youtube.com/@ahyaentendi)

**Session 2. Thursday, January 22.**

- Actividad: Confirmar si te faltan seis materias o menos para completar su plan de estudios.
- Actividad: Reportar avances en la formación de equipos, definición del tema y asignación de asesor(a).
- Tema: Tecnologías para la producción de documentos científicos.
- Actividad opcional: Instalar R, RStudio, ¿cómo producir documentos PDF en Quarto? Siga estas instrucciones de Wei Miao para instalar los programas en tu computadora: [Instrucciones escritas](https://weim-mkt.github.io/UCLMarketingAnalytics/R-installR.html). Aquí están las mismas instrucciones explicadas por Wei Miao en un video: [Instrucciones en video](https://www.youtube.com/watch?v=AP0R88qqmpI).
- Tema: Temas de investigación en finanzas.
- Actividad: Discusión de video. [Finding Research Topics - Robert Marquez](https://youtu.be/TuxcX4V0d08?si=B1Y6Dqb2frx2ZACV)

**Session 3. Thursday, January 29.**

- Obligatorio. Acepta las normativas del trabajo en equipo para esta clase: [Formulario](https://forms.gle/gb1AaiMtQSqe6BfeA).
- Obligatorio. Imprimir, firmar y entregar en clase las "Políticas para el Desarrollo de Proyecto de Evaluación Final (PEF)".
- Tarea 1: Entregar documento PDF con: (1) la confirmación de miembros de equipos, tema y asesor, (2) reporte de los objetivos de su proyecto. Estos pueden ser de uno a dos objetivos generales, con dos a tres objetivos específicos por cada objetivo general. El documento no debería exceder una página. La entrega es por Blackboard. La hora límite es 7:00pm de la sesión 3. Ponderación 5% de la calificación final.
- Actividad: Retroalimentación de la tarea 1.
- Tema: ¿Cómo presentar tu proyecto de investigación?
- Tema: La estructura del documento de tesis: @sec-structure.
- Actividad: Discusión de video. [https://www.fma.org/virtual-seminar](https://www.fma.org/virtual-seminar)
- Actividad: Discusión de video. [https://www.fma.org/student-virtual-seminar](https://www.fma.org/student-virtual-seminar)
- Videos de PEF1, primavera 2020: [Eq1](https://youtu.be/GGAdpuTCHIM?si=PfL70F-fiUAmWv_V), 
[Eq2](https://youtu.be/sl4hFMBH0HQ?si=PxtJTgRKEEEaDMdn), 
[Eq3](https://youtu.be/UdoB4foBcNo?si=Tw3a4mROs6UIE6vM), 
[Eq4](https://youtu.be/gyR1w93Nj_s?si=_O7ASruXNB0kiIXK).
- Videos de PEF1, primavera 2024: [Eq1](https://youtu.be/js6qeGYRbQc), 
[Eq2](https://youtu.be/tKuvjVn0cPU?si=56LQbVGH7DIA7dNz), 
[Eq3](https://youtu.be/QzwEBgACijI?si=wdp2-DjMhj5oreeK), 
[Eq4](https://www.youtube.com/watch?v=4ZvzEISD2QY&t=4s), 
[Eq5](https://youtu.be/_tZFvY8X7mI), 
[Eq6](https://www.youtube.com/watch?v=oSaVddKMf_M), 
[Eq7](https://youtu.be/setOjbQdcxo).
- Videos de PEF1, otoño 2024: 
[Eq1](https://www.youtube.com/watch?v=TUcfs9TuH6w), [Eq2](https://youtu.be/1NvKQogLiWw?si=AOD1pmJm00QKAmEs), [Eq3](https://www.youtube.com/watch?v=tBPpEof01WM).
- Videos de PEF1, primavera 2025: 
[Eq1](https://youtu.be/BuqeZKRb0vg),
[Eq2](https://www.youtube.com/watch?v=G4yavhVhjvg),
[Eq3](https://youtu.be/bJNVKldKNto),
[Eq4](https://www.youtube.com/watch?v=cpVu0EFpPqk),
[Eq5](https://youtu.be/CmPZeucThYI?si=sOs4dyGtOs69j1m1).
- Videos de PEF1, otoño 2025: 
[Eq1](https://www.youtube.com/watch?v=jqpbOo9rpqs),
[Eq2](https://youtu.be/UZHdbRdcVUM),
[Eq3](https://youtu.be/52iz_0wDngE?si=jh0ZJNj8l1LIqeNJ),
[Eq4](https://youtu.be/hZnWCPF-7qo),
[Eq5](https://youtu.be/8FuBc1Z04GM),
[Eq6](https://youtu.be/xcZQcXzT9h4?si=elURs4FzV9QOK651),
[Eq7](https://youtu.be/OkC0UNQov3s?si=uisAoUrk2-wzMREB),
[Eq8](https://youtu.be/DlTg8Vkx57I?si=g2KNqrbN9rvXEHaY).

**Session 4. Thursday, February 5.**

- Tarea 2: Entregar documento PDF con el draft de la revisión literaria. Una entrega por equipo. La entrega es por Blackboard. La hora límite es 7:00pm de la sesión 4. Ponderación 5% de la calificación final. El documento debe ser el mismo que el de la tarea 1, solo incluyan una nueva sección con el draft de la revisión literaria. 
- Actividad: Retroalimentación de la tarea 2.
- Actividad: Discusión de video. [Effective data storytelling for financial services](https://www.datacamp.com/resources/webinars/effective-data-storytelling-for-financial-services).

**Session 5. `r fontawesome::fa_i("heart", class = "fa-solid", style = "color: red;")` Thursday, February 12.**

- Tarea 3: Entregar documento PDF con revisión literaria y metodología. Una entrega por equipo. La entrega es por Blackboard. La hora límite es 7:00pm de la sesión 5. Ponderación 5% de la calificación final. El documento debe ser el mismo que el de la tarea 2, solo incluyan la nueva sección y correcciones pertinentes. 
- Actividad: Recibir retroalimentación de la tarea 3.
- *No conozco la fecha límite, pero deben completar la encuesta avanza 180 por favor.*

## `r fontawesome::fa("battery-half", fill = "red")` Part 2.

**Session 6. Thursday, February 19.**

- Tarea 4: Entregar documento PDF con introducción, revisión literaria y metodología. Una entrega por equipo. La entrega es por Blackboard. La hora límite es 7:00pm de la sesión 6. Ponderación 5% de la calificación final. El documento debe ser el mismo que el de la tarea 3, solo incluyan la nueva sección y correcciones pertinentes. 
- Actividad: Recibir retroalimentación de la tarea 4.
- Actividad: Completar coevaluación 1. Las coevaluaciones funcionan como en el resto de clases que imparto, pueden ver las instrucciones en el siguiente enlace [https://mlozanoqf.github.io/ARF1/#co-evaluation](https://mlozanoqf.github.io/ARF1/#co-evaluation). El enlace estará disponible en Blackboard en la sección "entregas". La hora límite es 7:00pm de la sesión 6.
- Reporte de calificaciones primer parcial.
- *No conozco la fecha límite, pero deben completar la encuesta avanza 180 por favor.*

**Session 7. Thursday, February 26.**

- Tarea 5: Entregar la tarea 4 con comentarios y un enlace de YouTube con un *elevator pitch*. Una entrega por equipo. La entrega es por Blackboard. La hora límite es 7:00pm de la sesión 7. Ponderación 10% de la calificación final. El documento debe ser el mismo que el de la tarea 4. Identifiquen claramente los cambios y mejoras que incorporaron en la primera página. El *elevator pitch* es una grabación de su presentación de máximo 2 minutos en donde todos los miembros del equipo participan para explicar su proyecto. La grabación es sin apoyos visuales. 
- Ejemplo de un *elevator pitch*: [PhD elevator pitch presentation by Fabienne Cheung](https://youtu.be/nayGkMLM9as?si=GaJSIR20lqTKod5h)
- Actividad: Recibir retroalimentación de la tarea 4.
- Tema: Habilidades para presentación.
- Actividad: Discusión de video. [Academic skills - presenting effectively - Part 1](https://youtu.be/pNIO5KkIq7Y?si=JGbpaWCQfVnQrdH2)
- Actividad: Discusión de video. [Academic skills - presenting effectively - Part 2](https://youtu.be/O-D9fZN01yk?si=bbA8WRbQCqTRX2p_)

**Session 8. Thursday, March 5.**

- Tarea 6: Presentar introducción, literatura y metodología. Presentaciones con apoyos visuales. Máximo 15 minutos por equipo. Ponderación 10% de la calificación final.
- Actividad: Recibir retroalimentación de la tarea 6.
- Actividad: Revisar la rúbrica de la entrega final.

**Session 9. Thursday, March 12.**

- Tarea 7: Presentar anteproyecto para alumnos y/o público externo. Presentaciones con apoyos visuales en clase. Máximo 15 minutos por equipo. Presentación presencial. Ponderación 15% de la calificación final.

**Session 10. `r fontawesome::fa_i("sun", class = "fa-solid")` Thursday, March 19.**

- Tarea 8: Presentar anteproyecto con comentarios. Presentaciones con apoyos visuales en clase. Máximo 15 minutos por equipo. Presentación presencial. Ponderación 15% de la calificación final.
- Actividad: Recibir retroalimentación de la tarea 8.

**Session 11. Thursday, March 26.**

- No hay sesión presencial ni por Zoom.
- Actividad: Hacer las grabaciones de las presentaciones. Aprovechen que todos tienen tiempo libre al menos de 7:00pm a 10:00pm para hacerlo. Presentaciones con apoyos visuales. Máximo 15 minutos por equipo. 
- Actividad: Completar coevaluación 2. Las coevaluaciones funcionan como en el resto de clases que imparto, pueden ver las instrucciones en el siguiente enlace [https://mlozanoqf.github.io/ARF1/#co-evaluation](https://mlozanoqf.github.io/ARF1/#co-evaluation). El enlace estará disponible en Blackboard en la sección "entregas". La hora límite es 7:00pm de la sesión 11.
- Reporte de calificaciones segundo parcial.

## `r fontawesome::fa("battery-three-quarters", fill = "orange")` Part 3.

**Holiday. `r fontawesome::fa("umbrella-beach")` Thursday, April 2.**

**Session 12. Thursday, April 9.**

- No hay sesión presencial ni por Zoom.
- Actividad: Hacer las grabaciones de las presentaciones. Aprovechen que todos tienen tiempo libre al menos de 7:00pm a 10:00pm para hacerlo. Presentaciones con apoyos visuales. Máximo 15 minutos por equipo. 

**Session 13. Thursday, April 16.**

- No hay sesión presencial ni por Zoom.
- Tarea 9: Entrega de enlace de videos de YouTube. Una entrega por equipo. La entrega es por Blackboard. La hora límite es 7:00pm de la sesión 13. Ponderación 30% de la calificación final. El documento debe ser el mismo que el de la tarea 5, solo incluyan el enlace del video de la presentación final en YouTube y correcciones pertinentes. Incluyan los apoyos visuales usados en la presentación. 

**Session 14. Thursday, April 23.**

- No hay sesión presencial ni por Zoom.
- Revisión de videos.
- Revisión de los los videos por parte de los profesores del departamento, del lunes 20 de abril al miércoles 29 de abril a las 6:00pm.
- *No conozco la fecha límite, pero deben completar la encuesta avanza 360 por favor.*

**Session 15. `r fontawesome::fa_i("children", class = "fa-solid")` Thursday, April 30.**

- No hay sesión presencial ni por Zoom.
- Entrega de calificaciones: 70 puntos de tareas más 30 de evaluación del video de presentación final por parte del comité de profesores evaluadores.

## `r fontawesome::fa("battery-full", fill = "green")` The end.

**Session 16. Thursday, May 7.**

- No hay sesión presencial ni por Zoom.
- Presentaciones en caso de reprobar la clase.
- Farewell `r fontawesome::fa_i("heart", class = "fa-solid", style = "color: red;")`.

# `r fontawesome::fa("calendar-alt")` UDEM: Calendario PEF2. 

Esta sección es exclusiva para aquellos equipos que hayan decidido que yo sea su supervisor de su proyecto PEF. Cada supervisor tiene una forma distinta de trabajar, con lo cual esta sección no debe considerarse como lineamientos generales. En PEF2 no tenemos sesiones como en un curso regular. El calendario no incluye juntas, ni otras actividades necesarias que no es posible anticipar.

## `r fontawesome::fa("battery-quarter", fill = "grey")` Part 1.

**Week 1. `r fontawesome::fa("handshake")` Mon-Fri, Jan 12-16.**

- Reading. Course syllabus (this document).
- Junta inicial para determinar los siguientes pasos.
- Si tienes interés en una licencia de DataCamp para este semestre envíame un email para dártela.
- Al menos durante este semestre es necesario que te suscribas al canal de YouTube [ahyaentendi](https://www.youtube.com/@ahyaentendi)

**Week 2. Mon-Fri, Jan 19-23.**

- Martín: Invitar a dos sinodales.

**Week 3. Mon-Fri, Jan 26-30.**

- Martín: Determinar las fechas de las presentaciones de medio término y la presentación final de acuerdo a la disponibilidad de horario de los sinodales.
- Martín: Reserva de salas para las presentaciones de medio término y la final.
- Martín: Reserva de la hora en la que van a pasar a la campana.

**Week 4. Mon-Fri, Feb 2-6.**

- Continua el avance regular por parte del equipo.
- Existen rúbricas y lineamientos para optar por la mención de excelencia. Sugiero que el equipo me solicite esos documentos.
 
**Week 5. `r fontawesome::fa_i("heart", class = "fa-solid", style = "color: red;")` Mon-Fri, Feb 9-13.**

- *No conozco la fecha límite, pero deben completar la encuesta avanza 180 por favor.*
- Continua el avance regular por parte del equipo.

**Week 6. Mon-Fri, Feb 16-20.**

- Continua el avance regular por parte del equipo.

**Week 7. Mon-Fri, Feb 23-27.**

- Entrega 1. La definición de la entrega depende de cada proyecto. Lo que es seguro es que deben entregar un avance sobre los resultados.
- Si el equipo lo solicita, podemos tener una coevaluación en el primer parcial.
- Reporte de calificaciones del primer parcial.

## `r fontawesome::fa("battery-half", fill = "red")` Part 2.

**Week 8. Mon-Fri, Mar 2-6.**

- Continua el avance regular por parte del equipo.

**Week 9. Mon-Fri, Mar 9-13.**

- Continua el avance regular por parte del equipo.

**Week 10. Mon-Fri, Mar 16-20.**

- Ensayos de presentaciones de medio término.

**Week 11. Mon-Fri, Mar 23-27.**

- Presentaciones de medio término.
- Si el equipo lo solicita, podemos tener una coevaluación en el segundo parcial.
- Reporte de calificaciones del segundo parcial.

## `r fontawesome::fa("battery-three-quarters", fill = "orange")` Part 3.

**Holiday. `r fontawesome::fa("umbrella-beach")` Mon-Fri, Mar 30-Apr 3.**

**Week 12. Mon-Fri, Apr 6-10.**

- Junta posterior a la presentación de medio término para determinar los siguientes pasos.

**Week 13. Mon-Fri, Apr 13-17.**

- Continua el avance regular por parte del equipo.

**Week 14. Mon-Fri, Apr 20-24.**

- Continua el avance regular por parte del equipo.
- *No conozco la fecha límite, pero deben completar la encuesta avanza 360 por favor.*

**Week 15. `r fontawesome::fa_i("children", class = "fa-solid")` Mon-Fri, Apr 27-May 1.**

- Ensayos de presentaciones finales.

**Week 16. `r fontawesome::fa("jedi-order")` Mon-Fri, May 4-8.**

- Registro del proyecto en Biblioteca. Los detalles se encuentran en la página electrónica de la biblioteca [https://udem.libguides.com/c.php?g=1142125](https://udem.libguides.com/c.php?g=1142125) Es importante que lo hagan con tiempo porque van a requerir recolectar firmas.
- Entrega del documento PEF por correo electrónico.

**Week 17. Mon-Fri, May 11-15.**

- Presentaciones finales.
- Farewell `r fontawesome::fa_i("heart", class = "fa-solid", style = "color: red;")`.
